parameters:
  mailer.transport: sendmail

services:
  application:
    class: VmApp\Infrastructure\UI\Console\Application
    arguments: [ '@service_container' ]
  #  event_dispatcher:
  #    class: Symfony\Component\EventDispatcher\EventDispatcher
  inmemorystorage:
    class: VmApp\Infrastructure\Database\InMemoryDatabase
  productrepository:
    class: VmApp\Infrastructure\Repositories\ProductRepository
    arguments: [ '@inmemorystorage' ]
  orderrepository:
    class: VmApp\Infrastructure\Repositories\OrderRepository
    arguments: [ '@inmemorystorage' ]
  moneyrepository:
    class: VmApp\Infrastructure\Repositories\CoinStockRepository
    arguments: [ '@inmemorystorage' ]
  changecalculator:
    class: VmApp\Domain\Model\Sales\MoneyChangeCalculator
  createorderhandler:
    class: VmApp\Application\Order\CreateOrderCommandHandler
    arguments: [ '@changecalculator', '@productrepository', '@orderrepository', '@moneyrepository' ]
  cancelorderhandler:
    class: VmApp\Application\Order\CancelOrderCommandHandler
  productqueryhandler:
    class: VmApp\Application\Product\ProductQueryHandler
    arguments: [ '@productrepository' ]
  coinstockqueryhandler:
    class: VmApp\Application\CoinsStock\CoinStockQueryHandler
    arguments: [ '@moneyrepository' ]
  createordercontroller:
    class: VmApp\Infrastructure\UI\Console\CreateOrderController
    arguments: [ '@createorderhandler' ]
  cancelordercontroller:
    class: VmApp\Infrastructure\UI\Console\CancelOrderController
    arguments: [ '@cancelorderhandler' ]
  consultingproductstockcontroller:
    class: VmApp\Infrastructure\UI\Console\ConsultingStockController
    arguments: [ '@productqueryhandler' ]
  consultingcoinstockcontroller:
    class: VmApp\Infrastructure\UI\Console\ConsultingStockController
    arguments: [ '@coinstockqueryhandler' ]
  coin005:
    class: VmApp\Domain\Model\CoinStock\CoinTypesValidators\CoinType_005
  coin010:
    class: VmApp\Domain\Model\CoinStock\CoinTypesValidators\CoinType_010
  coin025:
    class: VmApp\Domain\Model\CoinStock\CoinTypesValidators\CoinType_025
  coin100:
    class: VmApp\Domain\Model\CoinStock\CoinTypesValidators\CoinType_100
  coinvalidator:
    class: VmApp\Domain\Model\CoinStock\CoinValidator
    arguments: [ [ '@coin005', '@coin010', '@coin025', '@coin100' ] ]
#    calls:
#      - registerValidator: [ ['@coin005', '@coin010' ]
